name: Main

on:
  push:
    branches: [incrementalCrawl]
  repository_dispatch:

jobs:
  firstJob:
    name: first job
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "incrementalCrawl"
      - name: Run scripts
        run: |
          pip install -r requirements.txt
          echo "APPLICATION_ID=${{ secrets.GATSBY_ALGOLIA_APPLICATION_ID }}\nAPI_KEY=${{ secrets.GATSBY_ALGOLIA_API_KEY }}\nGITHUB_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}" > .env
          ./docsearch run algolia_configs/zh-tidb-v6.0.json --is_incremental
          git status
