name: Main

on:
  push:
    branches: [incrementalCrawl]
  repository_dispatch:

jobs:
  firstJob:
    name: first job
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "incrementalCrawl"
      - name: Run scripts
        run: |
          pip3 install pipenv
          pipenv install
          pipenv shell
          echo "APPLICATION_ID=${{ secrets.GATSBY_ALGOLIA_APPLICATION_ID }}\nAPI_KEY=${{ secrets.GATSBY_ALGOLIA_API_KEY }}\nGITHUB_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}" > .env
          sudo mkdir -p /data
          cp algolia_configs/latest_commit.json /data/latest_commit.json
          ./docsearch run algolia_configs/zh-tidb-v6.0.json --is_incremental
          cp /data/latest_commit.json algolia_configs/latest_commit.json
          git status
